spring.application.name=tasklist

# Configuraci\u00f3n de base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/task_list
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# Hace que Hibernate muestre en la consola todos los comandos SQL que ejecuta tu aplicaci\u00f3n a trav\u00e9s de JPA.
spring.jpa.show-sql=true

#H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console


